export const persons = [
  {
    id: 'vincent',
    name: 'Vincent Porret',
    vehicle: 'Skoda Octavia Combi 1.8 TSI Swiss Line 25 4x4 DSG',
    plate: 'VD 4499',
    dob: '05.12.1994',
    age: 31,
    firstReg: '06.10.2017',
    catalogPrice: "33'790",
    accessories: "3'379",
    km: '7\'000 – 15\'000 km',
    propulsion: 'Essence',
    showCP: false,
    analysis: 'La Vaudoise est la moins chère en casco complète (1\'404 CHF), devançant AXA de 40 CHF seulement. AXA offre cependant le libre choix du garage et la RC la moins chère (399 CHF). La Mobilière est intéressante grâce à sa protection juridique incluse et sa ristourne 10% (~159 CHF), qui ramènerait sa prime effective à ~1\'427 CHF — presque au niveau de la Vaudoise. Zurich est la plus chère (1\'785 CHF) mais propose le contrat le plus court (2028) et la garantie à vie Help Points. Attention aux incohérences AXA : les deux offres ne déclarent pas les mêmes antécédents.',
    note: 'Les deux offres AXA ne déclarent pas les mêmes antécédents : AXA Casco complète déclare « pas d\'assureur précédent », aucun sinistre. AXA Casco partielle déclare assureur précédent Zurich, 2 sinistres (1 RC + 1 collision en 2024).',
    offers: {
      cascoComplete: [
        { insurer: 'AXA', total: 1443.94, primeNette: 1367.68, taxes: 76.26,
          rc: 399.30, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: 2000,
          collision: 303.90, degreCollision: '30%', franchiseCollision25: 1000, franchiseCollision25minus: 2000,
          cascoPartielle: 329.10, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui (vitres avant/arrière/latérales)', fouines: true, animaux: true, vandalisme: 'Oui (sans rayures)',
          phares: 'Oui (38.56 CHF, fr. 0)', dommagesParc: false, habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000, 30.72 CHF, fr. 0)',
          bonus: 'Oui (158.75 CHF, 2 sin./an)', fauteGrave: 'Oui (39.32 CHF)',
          depannage: 'Oui Europe (68.03 CHF, 10\'000/évt)', vehiculeRemplacement: false, protectionJuridique: false, accidentOccupants: false,
          mobilite: false, cyber: false,
          indemnisation: 'Valeur vénale majorée',
          garageLibre: true,
          contratDebut: '24.02.2026', contratFin: '31.03.2029', resiliation: 'Annuelle (3 mois préavis)',
          noteSpeciale: 'Rabais longue durée dispo (3 ans = 3%)'
        },
        { insurer: 'Mobilière', total: 1585.51, primeNette: 1502.24, taxes: 83.27,
          rc: 540.75, degreRC: '0/35%', franchiseRC25: 0, franchiseRC25minus: 1000,
          collision: 943.59, degreCollision: '0/35%', franchiseCollision25: 1000, franchiseCollision25minus: null,
          cascoPartielle: 0, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui (élargi, phares + éléments en verre)', fouines: true, animaux: true, vandalisme: true,
          phares: 'Oui (élargi, cond. 210)', dommagesParc: false, habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000, 17.90 CHF)',
          bonus: 'Oui (inclus, cond. 634)', fauteGrave: 'Oui (inclus, cond. 634)',
          depannage: 'CarAssistance 24/7 (inclus)', vehiculeRemplacement: '–', protectionJuridique: 'Oui (CG + JurLine)', accidentOccupants: false,
          mobilite: false, cyber: false,
          indemnisation: '–',
          garageLibre: false,
          contratDebut: '25.02.2026', contratFin: '31.01.2032', resiliation: 'Annuelle (3 mois, cond. 951)',
          noteSpeciale: 'Ristourne 10% possible (~159 CHF). Contrat long (2032).'
        },
        { insurer: 'Vaudoise', total: 1403.60, primeNette: 1328.90, taxes: 74.70,
          rc: 548.10, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: null,
          collision: 330.10, degreCollision: '30%', franchiseCollision25: 1000, franchiseCollision25minus: null,
          cascoPartielle: 450.70, franchiseCP: 0,
          cascoDetail: { vol: 36.80, incendie: 185.80, brisGlaces: 114.50, dommagesParticuliers: 90.40, effetsPerso: 23.20 },
          vol: true, incendie: true, brisGlaces: 'Oui (avec phares)', fouines: true, animaux: true, vandalisme: true,
          phares: '(inclus bris de glaces)', dommagesParc: 'Non désiré', habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000, 23.20 CHF)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: 'Assistance 24/7 (0800 811 911)', vehiculeRemplacement: 'Non désiré', protectionJuridique: false, accidentOccupants: 'Non désiré',
          mobilite: 'Non désiré', cyber: false,
          indemnisation: 'Valeur de base majorée',
          garageLibre: false,
          contratDebut: '24.02.2026', contratFin: '31.12.2029', resiliation: 'Renouvellement tacite',
          noteSpeciale: 'Coopérative : ristournes possibles (44 mio CHF en 2025)'
        },
        { insurer: 'Zurich', total: 1784.90, primeNette: 1691.60, taxes: 93.30,
          rc: 588.50, degreRC: '–', franchiseRC25: 0, franchiseRC25minus: 1000,
          collision: 521.50, degreCollision: '–', franchiseCollision25: 1000, franchiseCollision25minus: 1000,
          cascoPartielle: 508.30, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui PLUS (fr. 0)', fouines: true, animaux: true, vandalisme: true,
          phares: 'Oui (PLUS)', dommagesParc: false, habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: 'Oui Europe (73.30 CHF)', vehiculeRemplacement: false, protectionJuridique: false, accidentOccupants: false,
          mobilite: false, cyber: false,
          indemnisation: '–',
          garageLibre: 'Oui (réparation auto-organisée)',
          contratDebut: '24.02.2026', contratFin: '31.12.2028', resiliation: 'Annuelle (3 mois, CP 0200)',
          noteSpeciale: 'Help Points : garantie à vie sur réparations'
        },
      ],
      cascoPartielle: [
        { insurer: 'AXA', total: 1022.52, primeNette: 966.33, taxes: 56.19,
          rc: 399.30, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: 2000,
          cascoPartielle: 398.38, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: true, fouines: true, animaux: true, vandalisme: 'Oui (sans rayures)',
          phares: 'Oui (38.56, fr. 0)', effetsPerso: 'Oui (2\'000, 30.72 CHF)',
          bonus: 'Oui (74.73 CHF, 2 sin./an)', fauteGrave: 'Oui (25.89 CHF)',
          depannage: 'Oui Europe (68.03 CHF)', vehiculeRemplacement: false, protectionJuridique: false,
          garageLibre: true, indemnisation: 'Valeur vénale majorée',
          contratDebut: '24.02.2026', contratFin: '31.03.2029', resiliation: 'Annuelle (3 mois)'
        },
        { insurer: 'Mobilière', total: 1063.36, primeNette: 1004.95, taxes: 58.41,
          rc: 540.75, degreRC: '0/35%', franchiseRC25: 0, franchiseRC25minus: 1000,
          cascoPartielle: 450.00, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui (élargi)', fouines: true, animaux: true, vandalisme: true,
          effetsPerso: 'Oui (2\'000, 14.20 CHF)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: 'CarAssistance 24/7', vehiculeRemplacement: '–', protectionJuridique: 'Oui (CG + JurLine)',
          garageLibre: false, indemnisation: '–',
          contratDebut: '25.02.2026', contratFin: '31.01.2032', resiliation: 'Annuelle (cond. 951)',
          noteSpeciale: 'Ristourne 10% possible (~106 CHF)'
        },
        { insurer: 'Vaudoise', total: 1057.00, primeNette: 998.80, taxes: 58.20,
          rc: 548.10, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: null,
          cascoPartielle: 450.70, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui (avec phares)', fouines: true, animaux: true, vandalisme: true,
          effetsPerso: 'Oui (2\'000, 23.20 CHF)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: 'Assistance 24/7', vehiculeRemplacement: 'Non désiré', protectionJuridique: false,
          garageLibre: false, indemnisation: 'Valeur de base majorée',
          contratDebut: '24.02.2026', contratFin: '31.12.2029', resiliation: 'Renouvellement tacite'
        },
        { insurer: 'Zurich', total: 1233.40, primeNette: 1166.40, taxes: 67.00,
          rc: 584.80, degreRC: '–', franchiseRC25: 0, franchiseRC25minus: 1000,
          cascoPartielle: 508.30, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui PLUS', fouines: true, animaux: true, vandalisme: true,
          effetsPerso: 'Oui (2\'000)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: 'Oui Europe (73.30 CHF)', vehiculeRemplacement: false, protectionJuridique: false,
          garageLibre: 'Oui (réparation auto-organisée)', indemnisation: '–',
          contratDebut: '24.02.2026', contratFin: '31.12.2028', resiliation: 'Annuelle (3 mois, CP 0200)'
        },
      ],
    },
    proscons: {
      'AXA': {
        pros: ['RC la moins chère (399 CHF)', 'Casco partielle la moins chère (1\'023 CHF)', 'Dépannage Europe inclus (10\'000 CHF/évt)', 'Libre choix du garage', 'Résiliation annuelle (3 mois)'],
        cons: ['Pas de véhicule de remplacement', 'Pas de protection juridique', 'Bonus/faute grave facturés en supplément', 'Vandalisme sans rayures uniquement'],
      },
      'Vaudoise': {
        pros: ['Casco complète la moins chère (1\'404 CHF)', 'Bonus et faute grave inclus', 'Assistance 24/7 gratuite', 'Coopérative : ristournes possibles'],
        cons: ['RC plus chère (548 CHF)', 'Pas de dépannage Europe structuré', 'Pas de protection juridique', 'Pas de libre choix du garage mentionné'],
      },
      'Mobilière': {
        pros: ['Protection juridique incluse (CG + JurLine)', 'Ristourne 10% (~159 CHF)', 'Bris de glaces élargi (phares + verre)', 'CarAssistance 24/7', 'Bonus et faute grave inclus'],
        cons: ['Prime élevée (1\'586 CHF en CC)', 'Contrat très long (jusqu\'au 31.01.2032)', 'RC chère (541 CHF)', 'Casco complète non détaillée'],
      },
      'Zurich': {
        pros: ['Help Points : garantie à vie sur réparations', 'Mobilité garantie via Help Point', 'Dépannage Europe inclus', 'Bris de glaces PLUS', 'Bonus et faute grave inclus', 'Contrat le plus court (2028)'],
        cons: ['La plus chère (1\'785 CHF en CC, 1\'233 en CP)', 'RC la plus chère (585-589 CHF)', 'Véhicules parqués, pneus/jantes : non couverts'],
      },
    },
  },

  // ===== MÉLANIE =====
  {
    id: 'melanie',
    name: 'Mélanie Porret',
    vehicle: 'Opel Mokka 1.4i 16V Turbo Cosmo 4WD',
    plate: 'VD 107839',
    dob: '22.05.1992',
    age: 33,
    firstReg: '31.10.2016',
    catalogPrice: "30'850",
    accessories: "3'085",
    km: 'jusqu\'à 15\'000 km',
    propulsion: 'Essence',
    showCP: true,
    analysis: 'La Vaudoise domine nettement en casco complète (1\'192 CHF) et partielle (860 CHF), avec bonus et faute grave inclus. AXA est compétitive en CP (876 CHF) et offre la RC la moins chère (367 CHF) + libre choix du garage. L\'offre Vaudoise Abrézol affiche 1\'375 CHF mais une prime négociée à CHF 1\'087 a été obtenue (rabais 287 CHF) — ce qui la rend très compétitive, bien qu\'elle ait une franchise bris de glaces de CHF 200 et concerne un véhicule légèrement différent (VD 104839 Color Edition). La Mobilière propose la protection juridique et la ristourne 10%, mais reste chère. Zurich est la plus onéreuse dans les deux variantes.',
    offers: {
      cascoComplete: [
        { insurer: 'AXA', total: 1231.39, primeNette: 1165.63, taxes: 65.76,
          rc: 366.90, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: 2000,
          collision: 267.30, degreCollision: '30%', franchiseCollision25: 1000, franchiseCollision25minus: 2000,
          cascoPartielle: 253.99, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui (vitres avant/arrière/latérales)', fouines: true, animaux: true, vandalisme: 'Oui (sans rayures)',
          phares: 'Oui (34.37 CHF, fr. 0)', dommagesParc: false, habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000, 26.74 CHF, fr. 0)',
          bonus: 'Oui (113.76 CHF, 1 sinistre/an)', fauteGrave: 'Oui (34.71 CHF)',
          depannage: 'Oui Europe (67.86 CHF, 10\'000/évt)', vehiculeRemplacement: false, protectionJuridique: false, accidentOccupants: false,
          indemnisation: 'Valeur vénale majorée', garageLibre: true,
          contratDebut: '24.02.2026', contratFin: '31.03.2029', resiliation: 'Annuelle (3 mois)'
        },
        { insurer: 'Mobilière', total: 1303.81, primeNette: 1234.42, taxes: 69.39,
          rc: 475.99, degreRC: '0/35%', franchiseRC25: 0, franchiseRC25minus: 1000,
          collision: 740.53, degreCollision: '0/35%', franchiseCollision25: 1000, franchiseCollision25minus: null,
          cascoPartielle: 0, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui (élargi, cond. 210)', fouines: true, animaux: true, vandalisme: true,
          phares: 'Oui (élargi)', dommagesParc: false, habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000, 17.90 CHF)',
          bonus: 'Oui (inclus, cond. 634)', fauteGrave: 'Oui (inclus, cond. 634)',
          depannage: 'CarAssistance 24/7 (inclus)', vehiculeRemplacement: '–', protectionJuridique: 'Oui (CG + JurLine)', accidentOccupants: false,
          indemnisation: '–', garageLibre: false,
          contratDebut: '25.02.2026', contratFin: '31.01.2032', resiliation: 'Annuelle (3 mois, cond. 951)',
          noteSpeciale: 'Ristourne 10% possible (~130 CHF)'
        },
        { insurer: 'Vaudoise', total: 1192.20, primeNette: 1128.30, taxes: 63.90,
          rc: 435.80, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: null,
          collision: 316.10, degreCollision: '30%', franchiseCollision25: 1000, franchiseCollision25minus: null,
          cascoPartielle: 376.40, franchiseCP: 0,
          cascoDetail: { vol: 25.10, incendie: 158.40, brisGlaces: 103.80, dommagesParticuliers: 69.40, effetsPerso: 19.70 },
          vol: true, incendie: true, brisGlaces: 'Oui (avec phares)', fouines: true, animaux: true, vandalisme: true,
          phares: '(inclus bris de glaces)', dommagesParc: 'Non désiré', habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000, 19.70 CHF)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: 'Assistance 24/7 (0800 811 911)', vehiculeRemplacement: 'Non désiré', protectionJuridique: false, accidentOccupants: 'Non désiré',
          indemnisation: 'Valeur de base majorée', garageLibre: false,
          contratDebut: '24.02.2026', contratFin: '31.12.2029', resiliation: 'Renouvellement tacite',
          noteSpeciale: 'Coopérative (44 mio CHF en 2025)'
        },
        { insurer: 'Zurich', total: 1518.60, primeNette: 1438.10, taxes: 80.50,
          rc: 591.10, degreRC: '–', franchiseRC25: 0, franchiseRC25minus: 1000,
          collision: 437.60, degreCollision: '–', franchiseCollision25: 1000, franchiseCollision25minus: 1000,
          cascoPartielle: 344.50, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui PLUS (fr. 0)', fouines: true, animaux: true, vandalisme: true,
          phares: 'Oui (PLUS)', dommagesParc: false, habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (5\'000)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: 'Oui Europe (64.90 CHF)', vehiculeRemplacement: false, protectionJuridique: false, accidentOccupants: false,
          indemnisation: '–', garageLibre: 'Oui (réparation auto-organisée)',
          contratDebut: '24.02.2026', contratFin: '31.12.2028', resiliation: 'Annuelle (3 mois, CP 0200)',
          noteSpeciale: 'Help Points, garantie à vie réparations'
        },
        { insurer: 'Vaudoise Abrézol', total: 1374.80, primeNette: 1301.60, taxes: 73.20,
          rc: 514.30, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: null,
          collision: 373.30, degreCollision: '30%', franchiseCollision25: 1000, franchiseCollision25minus: null,
          cascoPartielle: 414.00, franchiseCP: 0,
          cascoDetail: { vol: 29.50, incendie: 186.30, brisGlaces: 93.40, dommagesParticuliers: 81.60, effetsPerso: 23.20 },
          vol: true, incendie: true, brisGlaces: 'Oui (avec phares, fr. 200)', fouines: true, animaux: true, vandalisme: true,
          phares: '(inclus bris de glaces, fr. 200)', dommagesParc: 'Non désiré', habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000, 23.20 CHF)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: 'Assistance 24/7 (0800 811 911)', vehiculeRemplacement: 'Non désiré', protectionJuridique: false, accidentOccupants: 'Non désiré',
          indemnisation: 'Valeur de base majorée', garageLibre: false,
          contratDebut: '07.01.2026', contratFin: '31.12.2029', resiliation: 'Renouvellement tacite',
          noteSpeciale: 'Agent Abrézol. Prime négociée à CHF 1\'087 (rabais 287 CHF vs offre initiale 1\'375). Protection bonus retirable (-113 CHF). Effets perso retirables (-23.20 CHF). Ristourne Vaudoise ~10% tous les 2 ans. Franchise bris de glaces CHF 200 ! NB : offre sur plaque VD 104839 (Color Edition), pas VD 107839 (Cosmo).'
        },
      ],
      cascoPartielle: [
        { insurer: 'AXA', total: 876.28, primeNette: 827.43, taxes: 48.85,
          rc: 366.90, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: 2000,
          cascoPartielle: 253.99, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: true, fouines: true, animaux: true, vandalisme: 'Oui (sans rayures)',
          phares: 'Oui (34.37, fr. 0)', effetsPerso: 'Oui (2\'000, 26.74 CHF)',
          bonus: 'Oui (54.66 CHF)', fauteGrave: 'Oui (22.91 CHF)',
          depannage: 'Oui Europe (67.86 CHF)', vehiculeRemplacement: false, protectionJuridique: false,
          garageLibre: true, indemnisation: 'Valeur vénale majorée',
          contratDebut: '24.02.2026', contratFin: '31.03.2029', resiliation: 'Annuelle (3 mois)'
        },
        { insurer: 'Mobilière', total: 964.94, primeNette: 911.69, taxes: 53.25,
          rc: 475.99, degreRC: '0/35%', franchiseRC25: 0, franchiseRC25minus: 1000,
          cascoPartielle: 421.50, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui (élargi)', fouines: true, animaux: true, vandalisme: true,
          effetsPerso: 'Oui (2\'000, 14.20 CHF)',
          bonus: 'Oui (inclus, cond. 634)', fauteGrave: 'Oui (inclus)',
          depannage: 'CarAssistance 24/7', vehiculeRemplacement: '–', protectionJuridique: 'Oui (CG + JurLine)',
          garageLibre: false, indemnisation: '–',
          contratDebut: '25.02.2026', contratFin: '31.01.2032', resiliation: 'Annuelle (cond. 951)',
          noteSpeciale: 'Ristourne 10% possible'
        },
        { insurer: 'Vaudoise', total: 860.30, primeNette: 812.20, taxes: 48.10,
          rc: 435.80, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: null,
          cascoPartielle: 376.40, franchiseCP: 0,
          cascoDetail: { vol: 25.10, incendie: 158.40, brisGlaces: 103.80, dommagesParticuliers: 69.40, effetsPerso: 19.70 },
          vol: true, incendie: true, brisGlaces: 'Oui (avec phares)', fouines: true, animaux: true, vandalisme: true,
          effetsPerso: 'Oui (2\'000, 19.70 CHF)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: 'Assistance 24/7', vehiculeRemplacement: 'Non désiré', protectionJuridique: false,
          garageLibre: false, indemnisation: 'Valeur de base majorée',
          contratDebut: '24.02.2026', contratFin: '31.12.2029', resiliation: 'Renouvellement tacite'
        },
        { insurer: 'Zurich', total: 1047.50, primeNette: 989.50, taxes: 58.00,
          rc: 580.50, degreRC: '–', franchiseRC25: 0, franchiseRC25minus: 1000,
          cascoPartielle: 344.10, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui PLUS', fouines: true, animaux: true, vandalisme: true,
          effetsPerso: 'Oui (5\'000)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: 'Oui Europe (64.90 CHF)', vehiculeRemplacement: false, protectionJuridique: false,
          garageLibre: 'Oui (réparation auto-organisée)', indemnisation: '–',
          contratDebut: '24.02.2026', contratFin: '31.12.2028', resiliation: 'Annuelle (3 mois, CP 0200)'
        },
      ],
    },
    proscons: {
      'AXA': {
        pros: ['RC la moins chère (367 CHF)', 'CP la moins chère (876 CHF)', 'Dépannage Europe (10\'000/évt)', 'Libre choix du garage'],
        cons: ['Bonus/faute grave en supplément', 'Pas de protection juridique', 'Vandalisme sans rayures uniquement'],
      },
      'Vaudoise': {
        pros: ['CC la moins chère (1\'192 CHF)', 'CP 2e moins chère (860 CHF)', 'Bonus et faute grave inclus', 'Assistance 24/7 incluse'],
        cons: ['RC plus chère (436 CHF)', 'Pas de protection juridique'],
      },
      'Mobilière': {
        pros: ['Protection juridique incluse', 'Ristourne 10%', 'Bris de glaces élargi', 'Bonus/faute grave inclus'],
        cons: ['Prime élevée', 'Contrat long (2032)', 'RC chère (476 CHF)'],
      },
      'Zurich': {
        pros: ['Help Points, garantie à vie', 'Bris de glaces PLUS', 'Effets personnels 5\'000 CHF', 'Contrat court (2028)'],
        cons: ['La plus chère dans les deux variantes', 'RC très chère (580-591 CHF)'],
      },
      'Vaudoise Abrézol': {
        pros: ['Prime négociée à CHF 1\'087 (rabais 287 CHF)', 'Bonus et faute grave inclus', 'Assistance 24/7 incluse', 'Ristourne Vaudoise ~10% tous les 2 ans', 'Options modulables (bonus -113, effets perso -23.20)'],
        cons: ['Offre initiale plus chère que Vaudoise directe (1\'375 vs 1\'192)', 'RC plus chère (514 vs 436 CHF)', 'Franchise bris de glaces CHF 200 (unique dans le comparatif)', 'Offre sur plaque/véhicule différent (VD 104839 Color Edition)'],
      },
    },
  },

  // ===== CLAUDINE =====
  {
    id: 'claudine',
    name: 'Claudine Porret',
    vehicle: 'Volvo XC40 T5 AWD Momentum Gear',
    plate: 'VD 171093',
    dob: '09.02.1965',
    age: 61,
    firstReg: '19.09.2018',
    catalogPrice: "52'600",
    accessories: "14'807",
    km: 'jusqu\'à 15\'000 km',
    propulsion: 'Essence, 248 CV',
    showCP: false,
    analysis: 'La Vaudoise est la moins chère (1\'439 CHF) mais ATTENTION : la faute grave n\'est PAS couverte, ni en RC ni en collision. En cas de sinistre sous l\'influence d\'alcool ou de faute grave, la Vaudoise pourrait réduire ses prestations ou exercer un recours. La Mobilière (1\'545 CHF) inclut tout (juridique, bonus, faute grave, bris de glaces élargi) et offre une ristourne 10% (~155 CHF) qui la ramènerait à ~1\'390 CHF — moins chère que la Vaudoise, avec la faute grave couverte. AXA (1\'587 CHF) propose le libre choix du garage et un bonus 2 sinistres/an. Zurich est très chère (2\'036 CHF).',
    note: 'Attention : chez la Vaudoise, la couverture faute grave n\'est PAS souscrite (non désiré), ni en RC ni en collision. Cela peut avoir un impact en cas de sinistre.',
    offers: {
      cascoComplete: [
        { insurer: 'AXA', total: 1586.99, primeNette: 1504.29, taxes: 82.70,
          rc: 356.10, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: 2000,
          collision: 481.50, degreCollision: '30%', franchiseCollision25: 1000, franchiseCollision25minus: 2000,
          cascoPartielle: 320.07, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui (vitres avant/arrière/latérales)', fouines: true, animaux: true, vandalisme: 'Oui (sans rayures)',
          phares: 'Oui (34.45 CHF, fr. 0)', dommagesParc: false, habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000, 27.81 CHF, fr. 0)',
          bonus: 'Oui (200.15 CHF, 2 sin./an)', fauteGrave: 'Oui (43.35 CHF)',
          depannage: 'Oui Europe (40.86 CHF, 10\'000/évt)', vehiculeRemplacement: false, protectionJuridique: false, accidentOccupants: false,
          indemnisation: 'Valeur vénale majorée', garageLibre: true,
          contratDebut: '26.02.2026', contratFin: '31.03.2029', resiliation: 'Annuelle (3 mois)'
        },
        { insurer: 'Mobilière', total: 1544.89, primeNette: 1464.10, taxes: 80.79,
          rc: 463.68, degreRC: '0/35%', franchiseRC25: 0, franchiseRC25minus: 1000,
          collision: 982.52, degreCollision: '0/35%', franchiseCollision25: 1000, franchiseCollision25minus: null,
          cascoPartielle: 0, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui (élargi, cond. 210)', fouines: true, animaux: true, vandalisme: true,
          phares: 'Oui (élargi)', dommagesParc: false, habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000, 17.90 CHF)',
          bonus: 'Oui (inclus, cond. 634)', fauteGrave: 'Oui (inclus, cond. 634)',
          depannage: 'CarAssistance 24/7 (inclus)', vehiculeRemplacement: '–', protectionJuridique: 'Oui (CG + JurLine)', accidentOccupants: false,
          indemnisation: '–', garageLibre: false,
          contratDebut: '27.02.2026', contratFin: '28.02.2031', resiliation: 'Annuelle (3 mois, cond. 951)',
          noteSpeciale: 'Ristourne 10% possible (~155 CHF)'
        },
        { insurer: 'Vaudoise', total: 1438.90, primeNette: 1362.90, taxes: 76.00,
          rc: 498.70, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: null,
          collision: 419.90, degreCollision: '30%', franchiseCollision25: 1000, franchiseCollision25minus: null,
          cascoPartielle: 444.30, franchiseCP: 0,
          cascoDetail: { vol: 27.00, incendie: 181.40, brisGlaces: 150.50, dommagesParticuliers: 66.80, effetsPerso: 18.60 },
          vol: true, incendie: true, brisGlaces: 'Oui (avec phares)', fouines: true, animaux: true, vandalisme: true,
          phares: '(inclus bris de glaces)', dommagesParc: 'Non désiré', habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000, 18.60 CHF)',
          bonus: 'Oui (inclus)', fauteGrave: 'NON DÉSIRÉ',
          depannage: 'Assistance 24/7 (0800 811 911)', vehiculeRemplacement: 'Non désiré', protectionJuridique: false, accidentOccupants: 'Non désiré',
          indemnisation: 'Valeur de base majorée', garageLibre: false,
          contratDebut: '25.02.2026', contratFin: '31.12.2029', resiliation: 'Renouvellement tacite',
          noteSpeciale: 'ATTENTION : Faute grave NON couverte'
        },
        { insurer: 'Zurich', total: 2035.90, primeNette: 1930.20, taxes: 105.70,
          rc: 653.20, degreRC: '–', franchiseRC25: 0, franchiseRC25minus: 1000,
          collision: 751.80, degreCollision: '–', franchiseCollision25: 1000, franchiseCollision25minus: 1000,
          cascoPartielle: 459.00, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui PLUS (fr. 0)', fouines: true, animaux: true, vandalisme: true,
          phares: 'Oui (PLUS)', dommagesParc: false, habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: 'Oui Europe (66.20 CHF)', vehiculeRemplacement: false, protectionJuridique: false, accidentOccupants: false,
          indemnisation: '–', garageLibre: 'Oui (réparation auto-organisée)',
          contratDebut: '25.02.2026', contratFin: '31.12.2028', resiliation: 'Annuelle (3 mois, CP 0200)',
          noteSpeciale: 'Help Points, garantie à vie'
        },
      ],
    },
    proscons: {
      'AXA': {
        pros: ['RC la moins chère (356 CHF)', 'Libre choix du garage', 'Dépannage Europe (10\'000/évt)', 'Faute grave couverte'],
        cons: ['Bonus/faute grave en supplément (244 CHF)', 'Pas de protection juridique', 'Vandalisme sans rayures'],
      },
      'Vaudoise': {
        pros: ['La moins chère (1\'439 CHF)', 'Bonus inclus', 'Assistance 24/7'],
        cons: ['FAUTE GRAVE NON COUVERTE', 'RC plus chère (499 CHF)', 'Pas de protection juridique'],
      },
      'Mobilière': {
        pros: ['Protection juridique incluse', 'Bonus + faute grave inclus', 'Bris de glaces élargi', 'Ristourne 10%'],
        cons: ['Contrat jusqu\'au 28.02.2031', 'RC assez chère (464 CHF)'],
      },
      'Zurich': {
        pros: ['Help Points, garantie à vie', 'Bris de glaces PLUS', 'Bonus + faute grave inclus', 'Contrat court (2028)'],
        cons: ['La plus chère (2\'036 CHF)', 'RC très chère (653 CHF)'],
      },
    },
  },

  // ===== ANTOINE =====
  {
    id: 'antoine',
    name: 'Antoine Porret',
    vehicle: 'Audi SQ5 TDI quattro tiptronic',
    plate: 'VD 137965',
    dob: '05.03.1961',
    age: 65,
    firstReg: '23.06.2020',
    catalogPrice: "84'300",
    accessories: "8'430",
    km: 'jusqu\'à 15\'000 km',
    propulsion: 'Diesel, 347 CV',
    showCP: false,
    analysis: 'AXA est nettement la moins chère (1\'787 CHF), avec la RC la plus basse (347 CHF) et le libre choix du garage. La Vaudoise suit à 1\'848 CHF avec bonus et faute grave inclus, plus un rabais de 10% si la moto est aussi chez Vaudoise. La Mobilière (2\'466 CHF) est chère — sa collision seule coûte 1\'688 CHF — mais offre la protection juridique et une ristourne 10% (~247 CHF). Zurich est hors de prix (2\'918 CHF) avec une collision à 1\'313 CHF. L\'écart entre AXA et Zurich atteint 1\'131 CHF/an, soit 63% de plus.',
    note: null,
    offers: {
      cascoComplete: [
        { insurer: 'AXA', total: 1786.51, primeNette: 1694.49, taxes: 92.02,
          rc: 346.80, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: 2000,
          collision: 646.20, degreCollision: '30%', franchiseCollision25: 1000, franchiseCollision25minus: 2000,
          cascoPartielle: 353.71, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui (vitres avant/arrière/latérales)', fouines: true, animaux: true, vandalisme: 'Oui (sans rayures)',
          phares: 'Oui (31.56 CHF, fr. 0)', dommagesParc: false, habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000, 26.77 CHF, fr. 0)',
          bonus: 'Oui (195.95 CHF, 1 sin./an)', fauteGrave: 'Oui (54.33 CHF)',
          depannage: 'Oui Europe (39.17 CHF, 10\'000/évt)', vehiculeRemplacement: false, protectionJuridique: false, accidentOccupants: false,
          indemnisation: 'Valeur vénale majorée', garageLibre: true,
          contratDebut: '25.02.2026', contratFin: '31.03.2029', resiliation: 'Annuelle (3 mois)'
        },
        { insurer: 'Mobilière', total: 2465.60, primeNette: 2339.77, taxes: 125.83,
          rc: 632.61, degreRC: '0/35%', franchiseRC25: 0, franchiseRC25minus: 1000,
          collision: 1687.51, degreCollision: '0/35%', franchiseCollision25: 1000, franchiseCollision25minus: null,
          cascoPartielle: 0, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui (élargi, cond. 210)', fouines: true, animaux: true, vandalisme: true,
          phares: 'Oui (élargi)', dommagesParc: false, habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000, 19.65 CHF)',
          bonus: 'Oui (inclus, cond. 634)', fauteGrave: 'Oui (inclus, cond. 634)',
          depannage: 'CarAssistance 24/7 (inclus)', vehiculeRemplacement: '–', protectionJuridique: 'Oui (CG + JurLine)', accidentOccupants: false,
          indemnisation: '–', garageLibre: false,
          contratDebut: '26.02.2026', contratFin: '28.02.2031', resiliation: 'Annuelle (3 mois, cond. 951)',
          noteSpeciale: 'Ristourne 10% possible (~247 CHF). Contrat long (2031).'
        },
        { insurer: 'Vaudoise', total: 1847.90, primeNette: 1751.90, taxes: 96.00,
          rc: 563.40, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: null,
          collision: 619.70, degreCollision: '30%', franchiseCollision25: 1000, franchiseCollision25minus: null,
          cascoPartielle: 568.80, franchiseCP: 0,
          cascoDetail: { vol: 61.50, incendie: 233.50, brisGlaces: 179.80, dommagesParticuliers: 75.40, effetsPerso: 18.60 },
          vol: true, incendie: true, brisGlaces: 'Oui (avec phares)', fouines: true, animaux: true, vandalisme: true,
          phares: '(inclus bris de glaces)', dommagesParc: 'Non désiré', habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000, 18.60 CHF)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: 'Assistance 24/7 (0800 811 911)', vehiculeRemplacement: 'Non désiré', protectionJuridique: false, accidentOccupants: 'Non désiré',
          indemnisation: 'Valeur de base majorée', garageLibre: false,
          contratDebut: '25.02.2026', contratFin: '31.12.2029', resiliation: 'Renouvellement tacite',
          noteSpeciale: '10% rabais moto si autre contrat Vaudoise'
        },
        { insurer: 'Zurich', total: 2918.10, primeNette: 2770.30, taxes: 147.80,
          rc: 681.60, degreRC: '–', franchiseRC25: 0, franchiseRC25minus: 1000,
          collision: 1313.20, degreCollision: '–', franchiseCollision25: 1000, franchiseCollision25minus: 1000,
          cascoPartielle: 714.30, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui PLUS (fr. 0)', fouines: true, animaux: true, vandalisme: true,
          phares: 'Oui (PLUS)', dommagesParc: false, habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: 'Oui Europe (61.20 CHF)', vehiculeRemplacement: false, protectionJuridique: false, accidentOccupants: false,
          indemnisation: '–', garageLibre: 'Oui (réparation auto-organisée)',
          contratDebut: '25.02.2026', contratFin: '31.12.2028', resiliation: 'Annuelle (3 mois, CP 0200)'
        },
      ],
    },
    proscons: {
      'AXA': {
        pros: ['La moins chère (1\'787 CHF)', 'RC la moins chère (347 CHF)', 'Libre choix du garage', 'Dépannage Europe'],
        cons: ['Bonus/faute grave en supplément (250 CHF)', 'Vandalisme sans rayures'],
      },
      'Mobilière': {
        pros: ['Protection juridique incluse (CG + JurLine)', 'Bonus + faute grave inclus', 'Bris de glaces élargi', 'CarAssistance 24/7', 'Ristourne 10% (~247 CHF)'],
        cons: ['Très chère (2\'466 CHF)', 'RC chère (633 CHF)', 'Collision très chère (1\'688 CHF)', 'Contrat long (2031)'],
      },
      'Vaudoise': {
        pros: ['2e moins chère (1\'848 CHF)', 'Bonus + faute grave inclus', 'Assistance 24/7', '10% rabais sur moto'],
        cons: ['RC plus chère (563 CHF)'],
      },
      'Zurich': {
        pros: ['Bris de glaces PLUS', 'Bonus + faute grave inclus', 'Contrat court (2028)'],
        cons: ['La plus chère (2\'918 CHF)', 'Collision 1\'313 CHF (!)', 'RC très chère (682 CHF)'],
      },
    },
  },

  // ===== PETITE AUTO =====
  {
    id: 'petite-auto',
    name: 'Petite Auto',
    vehicle: 'Mercedes-Benz 300 SL',
    plate: 'VD 124209',
    dob: '05.03.1961 (Antoine)',
    age: 65,
    firstReg: '17.06.1987',
    catalogPrice: "Valeur convenue 50'000",
    km: 'sup. à 3\'000 km',
    propulsion: 'Essence, 180 CV',
    showCP: false,
    analysis: 'Pour cet oldtimer (valeur convenue CHF 50\'000), la Vaudoise est la moins chère (1\'021 CHF) avec des conditions N 113 intéressantes : collision étendue aux rayures/parking/transport, rallyes couverts, et la RC la plus basse (191 CHF). La Mobilière (1\'094 CHF) offre la protection juridique et le bonus/faute grave inclus, mais ATTENTION : le bris de glaces élargi n\'est PAS couvert (pas de cond. 210, oldtimer). AXA (1\'156 CHF) propose la protection Classic Car (pièces rechange, courses régularité) et le libre choix du garage. Zurich (1\'234 CHF) a la collision la moins chère (299 CHF) et la CP la moins chère (265 CHF), avec la valeur convenue + 20% de couverture préventive.',
    note: 'Véhicule vétéran/oldtimer. Valeur convenue CHF 50\'000. Conditions oldtimer spécifiques chez chaque assureur. Mobilière : PAS de bris de glaces élargi (pas de cond. 210).',
    offers: {
      cascoComplete: [
        { insurer: 'AXA', total: 1155.79, primeNette: 1094.30, taxes: 61.49,
          rc: 283.50, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: 2000,
          collision: 167.10, degreCollision: '30%', franchiseCollision25: 1000, franchiseCollision25minus: 2000,
          cascoPartielle: 306.64, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui (vitres avant/arrière/latérales)', fouines: true, animaux: true, vandalisme: 'Oui (sans rayures)',
          phares: 'Oui (37.65 CHF, fr. 0)', dommagesParc: false, habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000, 26.98 CHF, fr. 0)',
          bonus: 'Oui (92.14 CHF, 2 sin./an)', fauteGrave: 'Oui (25.31 CHF)',
          depannage: 'Oui Europe (46.69 CHF, 10\'000/évt)', vehiculeRemplacement: false, protectionJuridique: false,
          indemnisation: 'Valeur vénale, max somme assurance + 30%', garageLibre: true,
          contratDebut: '06.03.2026', contratFin: '31.03.2029', resiliation: 'Annuelle (3 mois)',
          noteSpeciale: 'Youngtimer/Oldtimer OPTIMA. Protection Classic Car incluse (108.29 CHF : pièces rechange, transport, courses régularité, frais inscription).'
        },
        { insurer: 'Mobilière', total: 1093.87, primeNette: 1035.33, taxes: 58.54,
          rc: 346.06, degreRC: '0/35%', franchiseRC25: 0, franchiseRC25minus: null,
          collision: 669.62, degreCollision: '0/35%', franchiseCollision25: 1000, franchiseCollision25minus: null,
          cascoPartielle: 0, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui (standard, PAS élargi — oldtimer)', fouines: true, animaux: true, vandalisme: true,
          phares: 'NON (pas de cond. 210, oldtimer)', dommagesParc: false, habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000, 19.65 CHF)',
          bonus: 'Oui (inclus, cond. 634)', fauteGrave: 'Oui (inclus)',
          depannage: 'CarAssistance 24/7', vehiculeRemplacement: '–', protectionJuridique: 'Oui (CG + JurLine)',
          indemnisation: 'Valeur actuelle 4 (oldtimer, cond. 207)', garageLibre: false,
          contratDebut: '26.02.2026', contratFin: '28.02.2031', resiliation: 'Annuelle (3 mois, cond. 951)',
          noteSpeciale: 'Oldtimer cond. 207 : bris de glaces SANS phares (pas de cond. 210). Courses chronométrées couvertes (régularité, < 50 km/h). Ristourne 10% possible (~109 CHF).'
        },
        { insurer: 'Vaudoise', total: 1021.00, primeNette: 967.00, taxes: 54.00,
          rc: 190.70, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: null,
          collision: 317.90, degreCollision: '30%', franchiseCollision25: 1000, franchiseCollision25minus: null,
          cascoPartielle: 458.40, franchiseCP: 0,
          cascoDetail: { vol: 25.40, incendie: 191.10, brisGlaces: 142.60, dommagesParticuliers: 76.10, effetsPerso: 23.20 },
          vol: true, incendie: true, brisGlaces: 'Oui (avec phares)', fouines: true, animaux: true, vandalisme: true,
          effetsPerso: 'Oui (2\'000, 23.20 CHF)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: '–', vehiculeRemplacement: '–', protectionJuridique: false,
          indemnisation: 'Valeur convenue (50\'000 CHF)', garageLibre: false,
          contratDebut: '25.02.2026', contratFin: '31.12.2029', resiliation: 'Renouvellement tacite',
          noteSpeciale: 'Oldtimer N 113, valeur convenue CHF 50\'000. Collision étendue (rayures, peinture, parc, transport). Rallyes oldtimer couverts. Conseil technique gratuit 1x/an. Bris de glace max 5\'000 CHF/sinistre.'
        },
        { insurer: 'Zurich', total: 1234.00, primeNette: 1167.10, taxes: 66.90,
          rc: 542.20, degreRC: '–', franchiseRC25: 0, franchiseRC25minus: 1000,
          collision: 299.00, degreCollision: '–', franchiseCollision25: 1000, franchiseCollision25minus: 1000,
          cascoPartielle: 264.70, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui PLUS', fouines: true, animaux: true, vandalisme: true,
          effetsPerso: 'Oui (2\'000)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: 'Oui Europe (61.20 CHF)', vehiculeRemplacement: false, protectionJuridique: false,
          indemnisation: 'Indemnité max. 50\'000 CHF', garageLibre: 'Oui (réparation auto-organisée)',
          contratDebut: '25.02.2026', contratFin: '31.12.2028', resiliation: 'Annuelle (3 mois, CP 0200)',
          noteSpeciale: 'Véhicule vétéran'
        },
      ],
    },
    proscons: {
      'AXA': {
        pros: ['RC bon marché (284 CHF)', 'Libre choix du garage', 'Dépannage Europe'],
        cons: ['3e plus chère (1\'156 CHF)', 'Collision chère (647 CHF)'],
      },
      'Mobilière': {
        pros: ['2e moins chère (1\'094 CHF)', 'Bonus + faute grave inclus', 'Protection juridique incluse', 'Courses de régularité couvertes (cond. 207)', 'Ristourne 10% possible (~109 CHF)'],
        cons: ['RC plus chère que Vaudoise (346 CHF)', 'Collision chère (670 CHF)', 'Bris de glaces SANS phares (pas de cond. 210, oldtimer)'],
      },
      'Vaudoise': {
        pros: ['La moins chère (1\'021 CHF)', 'RC très basse (191 CHF)', 'Valeur convenue 50\'000', 'Bonus + faute grave inclus'],
        cons: ['Pas de dépannage', 'Casco partielle chère (458 CHF)'],
      },
      'Zurich': {
        pros: ['Collision la moins chère (299 CHF)', 'CP la moins chère (265 CHF)', 'Dépannage Europe', 'Bris de glaces PLUS'],
        cons: ['La plus chère (1\'234 CHF)', 'RC très chère (542 CHF)'],
      },
    },
  },

  // ===== MOTO ANTOINE =====
  {
    id: 'moto-antoine',
    name: 'Moto Antoine',
    vehicle: 'BMW R 1200 R ABS (90 Jahre)',
    plate: 'VD 33976',
    dob: '05.03.1961 (Antoine)',
    age: 65,
    firstReg: '03.2016',
    catalogPrice: "15'100",
    km: '–',
    propulsion: 'Essence',
    showCP: false,
    analysis: 'AXA est clairement la moins chère (623 CHF) avec la RC la plus basse (149 CHF), le libre choix du garage et le dépannage Europe. La Mobilière suit à 677 CHF avec le bris de glaces élargi (cond. 210), la protection juridique et les effets personnels à 3\'000 CHF (mais sans vêtements/casque). Attention : la Mobilière impose la cond. 605 (pas de dépôt de plaque possible). La Vaudoise (788 CHF) a la collision la moins chère (132 CHF) mais une RC élevée (333 CHF). Zurich est la plus chère (867 CHF). Si la moto et un autre véhicule sont chez Vaudoise, 10% de rabais sur la prime moto.',
    offers: {
      cascoComplete: [
        { insurer: 'AXA', total: 622.94, primeNette: 590.44, taxes: 32.50,
          rc: 149.40, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: 2000,
          collision: 159.60, degreCollision: '30%', franchiseCollision25: 1000, franchiseCollision25minus: 2000,
          cascoPartielle: 88.18, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui (vitres avant/arrière/latérales)', fouines: true, animaux: true, vandalisme: 'Oui (sans rayures)',
          phares: 'Oui (9.69 CHF, fr. 0)', dommagesParc: false, habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (2\'000, 18.02 CHF)',
          bonus: 'Oui (100.10 CHF, 1 sin./an)', fauteGrave: 'Oui (33.76 CHF)',
          depannage: 'Oui Europe (31.69 CHF, 10\'000/évt)', vehiculeRemplacement: false, protectionJuridique: false,
          indemnisation: 'Valeur vénale majorée', garageLibre: true,
          contratDebut: '25.02.2026', contratFin: '31.03.2029', resiliation: 'Annuelle (3 mois)'
        },
        { insurer: 'Mobilière', total: 676.93, primeNette: 641.99, taxes: 34.94,
          rc: 197.31, degreRC: '0/35%', franchiseRC25: 0, franchiseRC25minus: 1000,
          collision: 444.68, degreCollision: '0/35%', franchiseCollision25: 1000, franchiseCollision25minus: null,
          cascoPartielle: 0, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui (élargi, cond. 210)', fouines: true, animaux: true, vandalisme: true,
          phares: 'Oui (élargi)', dommagesParc: false, habitacle: false, pneus: false, cles: false,
          effetsPerso: 'Oui (3\'000, sans vêtements/casque)',
          bonus: 'Oui (inclus, cond. 634)', fauteGrave: 'Oui (inclus, cond. 634)',
          depannage: 'CarAssistance 24/7 (inclus)', vehiculeRemplacement: '–', protectionJuridique: 'Oui (CG + JurLine)',
          indemnisation: '–', garageLibre: false,
          contratDebut: '26.02.2026', contratFin: '28.02.2031', resiliation: 'Annuelle (3 mois, cond. 951)',
          noteSpeciale: 'Cond. 605 : renonciation suspension (plaque ne peut être déposée). Ristourne 10% possible (~68 CHF).'
        },
        { insurer: 'Vaudoise', total: 787.70, primeNette: 743.80, taxes: 43.90,
          rc: 333.20, degreRC: '30%', franchiseRC25: 0, franchiseRC25minus: null,
          collision: 132.10, degreCollision: '30%', franchiseCollision25: 1000, franchiseCollision25minus: null,
          cascoPartielle: 278.50, franchiseCP: 0,
          cascoDetail: { vol: 25.60, incendie: 121.10, brisGlaces: 55.00, dommagesParticuliers: 58.20, effetsPerso: 18.60 },
          vol: true, incendie: true, brisGlaces: true, fouines: true, animaux: true, vandalisme: true,
          effetsPerso: 'Oui (2\'000, 18.60 CHF)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: '–', vehiculeRemplacement: '–', protectionJuridique: false,
          indemnisation: 'Valeur de base majorée', garageLibre: false,
          contratDebut: '25.02.2026', contratFin: '31.12.2029', resiliation: 'Renouvellement tacite'
        },
        { insurer: 'Zurich', total: 866.90, primeNette: 822.60, taxes: 44.30,
          rc: 229.50, degreRC: '–', franchiseRC25: 0, franchiseRC25minus: 1000,
          collision: 407.00, degreCollision: '–', franchiseCollision25: 1000, franchiseCollision25minus: 1000,
          cascoPartielle: 121.80, franchiseCP: 0,
          vol: true, incendie: true, brisGlaces: 'Oui PLUS', fouines: true, animaux: true, vandalisme: true,
          effetsPerso: 'Oui (2\'000)',
          bonus: 'Oui (inclus)', fauteGrave: 'Oui (inclus)',
          depannage: 'Oui Europe (64.30 CHF)', vehiculeRemplacement: false, protectionJuridique: false,
          indemnisation: '–', garageLibre: 'Oui (réparation auto-organisée)',
          contratDebut: '27.02.2026', contratFin: '31.12.2028', resiliation: 'Annuelle (3 mois, CP 0200)'
        },
      ],
    },
    proscons: {
      'AXA': {
        pros: ['La moins chère (623 CHF)', 'RC très basse (149 CHF)', 'Libre choix garage', 'Dépannage Europe'],
        cons: ['Bonus/faute grave en supplément'],
      },
      'Mobilière': {
        pros: ['2e moins chère (677 CHF)', 'Bonus + faute grave inclus', 'Protection juridique', 'Effets perso 3\'000 CHF'],
        cons: ['Collision chère (445 CHF)'],
      },
      'Vaudoise': {
        pros: ['Collision la moins chère (132 CHF)', 'Bonus + faute grave inclus'],
        cons: ['RC chère (333 CHF)', 'Pas de dépannage', 'Total élevé (788 CHF)'],
      },
      'Zurich': {
        pros: ['Bris de glaces PLUS', 'Dépannage Europe', 'Bonus + faute grave inclus'],
        cons: ['La plus chère (867 CHF)', 'Collision chère (407 CHF)'],
      },
    },
  },
];

export const insurerColors = {
  'AXA': '#00008f',
  'Mobilière': '#e30613',
  'Vaudoise': '#00a551',
  'Zurich': '#003399',
  'Vaudoise Abrézol': '#7cc992',
};
